// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartStay.Infrastructure.Persistance;

#nullable disable

namespace SmartStay.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(SmartStayDbContext))]
    [Migration("20260701112242_AddRenterIdToRoom")]
    partial class AddRenterIdToRoom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartStay.Domain.Entities.Amenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("amenities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44fd1192-34ea-4a44-b8c3-f2716cd744e6"),
                            Name = "Wifi"
                        },
                        new
                        {
                            Id = new Guid("48fd1822-33ea-4a44-b8e3-f2716dd744e6"),
                            Name = "Air conditioning"
                        },
                        new
                        {
                            Id = new Guid("fec3770b-b67c-4641-b176-af7a37249f3c"),
                            Name = "Pool"
                        },
                        new
                        {
                            Id = new Guid("256d5bde-c7dc-45ea-a357-31c171d1df9d"),
                            Name = "Garage"
                        },
                        new
                        {
                            Id = new Guid("b154c649-3194-4a5b-b9d1-2d3ae06c6e35"),
                            Name = "Gym"
                        },
                        new
                        {
                            Id = new Guid("618bfb12-002e-40f4-ae8c-9e02dffd1484"),
                            Name = "Spa"
                        },
                        new
                        {
                            Id = new Guid("48fd1893-3344-4a45-b7c3-f271acd744e6"),
                            Name = "Jacuzzi"
                        },
                        new
                        {
                            Id = new Guid("b2e57b8d-a882-45b8-9484-91e2ab8d4322"),
                            Name = "Breakfast"
                        },
                        new
                        {
                            Id = new Guid("48fd1813-3344-4a45-42c2-f2718cd741e5"),
                            Name = "Fireplace"
                        });
                });

            modelBuilder.Entity("SmartStay.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CheckOutDate")
                        .HasColumnType("datetime");

                    b.Property<DateTimeOffset>("CheckinDate")
                        .HasColumnType("datetime");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("RoomId", "CheckinDate", "CheckOutDate", "Status")
                        .HasDatabaseName("IX_Booking_RoomAvailability");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("SmartStay.Domain.Entities.CancellationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CancelledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DaysBeforeCheckin")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("CancellationLog", (string)null);
                });

            modelBuilder.Entity("SmartStay.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<double>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Locations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44fd2891-34ea-4a44-b8c3-f2716cd744e6"),
                            Address = "123 Main Street",
                            City = "New York",
                            Country = "United States",
                            Latitude = 40.712800000000001,
                            Longitude = -74.006,
                            PostalCode = "10001"
                        },
                        new
                        {
                            Id = new Guid("64a6ac13-7659-4434-9c39-403e98d7aa7e"),
                            Address = "456 Oxford Street",
                            City = "London",
                            Country = "United Kingdom",
                            Latitude = 51.507399999999997,
                            Longitude = -0.1278,
                            PostalCode = "SW1A 1AA"
                        },
                        new
                        {
                            Id = new Guid("d106dc17-6a8c-4e91-8355-9a1a756f7833"),
                            Address = "789 Champs-Élysées",
                            City = "Paris",
                            Country = "France",
                            Latitude = 48.8566,
                            Longitude = 2.3521999999999998,
                            PostalCode = "75008"
                        },
                        new
                        {
                            Id = new Guid("ebbff419-195d-4b57-af48-fac84d93f482"),
                            Address = "321 Shibuya Crossing",
                            City = "Tokyo",
                            Country = "Japan",
                            Latitude = 35.676200000000001,
                            Longitude = 139.65029999999999,
                            PostalCode = "150-0043"
                        },
                        new
                        {
                            Id = new Guid("f6aa2e4e-64b6-4608-b73d-89cb699f0382"),
                            Address = "555 Harbour Bridge Road",
                            City = "Sydney",
                            Country = "Australia",
                            Latitude = -33.8688,
                            Longitude = 151.20930000000001,
                            PostalCode = "2000"
                        });
                });

            modelBuilder.Entity("SmartStay.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("SmartStay.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("SmartStay.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId", "RoomId")
                        .IsUnique();

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("SmartStay.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("AverageRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(0f);

                    b.Property<string>("BedType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float>("PricePerNight")
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("RenterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("RenterId");

                    b.ToTable("Rooms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44d360a3-7433-4405-aaf2-32c2a3eebdf5"),
                            AverageRating = 4.8f,
                            BedType = "King",
                            Capacity = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 11, 22, 42, 173, DateTimeKind.Unspecified).AddTicks(1602), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Spacious room with stunning ocean views",
                            LocationId = new Guid("44fd2891-34ea-4a44-b8c3-f2716cd744e6"),
                            Name = "Deluxe Ocean View",
                            PricePerNight = 250f,
                            RenterId = new Guid("019e666d-05fb-7de1-9964-45e0e028a38a"),
                            Size = 45
                        },
                        new
                        {
                            Id = new Guid("487b0929-3600-450c-928a-5d0e9bcefaec"),
                            AverageRating = 4.6f,
                            BedType = "Queen",
                            Capacity = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 11, 22, 42, 173, DateTimeKind.Unspecified).AddTicks(1999), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Perfect for families, with two bedrooms and a living area",
                            LocationId = new Guid("64a6ac13-7659-4434-9c39-403e98d7aa7e"),
                            Name = "Family Suite",
                            PricePerNight = 350f,
                            RenterId = new Guid("019e666d-05fb-7de1-9964-45e0e028a38a"),
                            Size = 75
                        },
                        new
                        {
                            Id = new Guid("cf5106c1-8fe1-4889-b905-c7810f2eb519"),
                            AverageRating = 4.4f,
                            BedType = "Single",
                            Capacity = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 11, 22, 42, 173, DateTimeKind.Unspecified).AddTicks(2044), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Ideal for business travelers with work desk and high-speed internet",
                            LocationId = new Guid("d106dc17-6a8c-4e91-8355-9a1a756f7833"),
                            Name = "Business Executive",
                            PricePerNight = 180f,
                            RenterId = new Guid("019e666d-05fb-7de1-9964-45e0e028a38a"),
                            Size = 30
                        },
                        new
                        {
                            Id = new Guid("a6a7acdf-88c2-4fd2-b12e-a387d689f3db"),
                            AverageRating = 4.9f,
                            BedType = "King",
                            Capacity = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 11, 22, 42, 173, DateTimeKind.Unspecified).AddTicks(2048), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Cozy room perfect for couples with fireplace and jacuzzi",
                            LocationId = new Guid("ebbff419-195d-4b57-af48-fac84d93f482"),
                            Name = "Romantic Getaway",
                            PricePerNight = 300f,
                            RenterId = new Guid("019e666d-05fb-7de1-9964-45e0e028a38a"),
                            Size = 40
                        },
                        new
                        {
                            Id = new Guid("097758cd-3def-4b95-8d79-491a56f818b9"),
                            AverageRating = 4.2f,
                            BedType = "Single",
                            Capacity = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 11, 22, 42, 173, DateTimeKind.Unspecified).AddTicks(2052), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Compact yet comfortable studio with kitchenette",
                            LocationId = new Guid("f6aa2e4e-64b6-4608-b73d-89cb699f0382"),
                            Name = "Studio Apartment",
                            PricePerNight = 120f,
                            RenterId = new Guid("019e666d-05fb-7de1-9964-45e0e028a38a"),
                            Size = 25
                        });
                });

            modelBuilder.Entity("SmartStay.Domain.Entities.RoomAmenity", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AmenityId")
                        .HasColumnType("uuid");

                    b.HasKey("RoomId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("room_amenities", (string)null);

                    b.HasData(
                        new
                        {
                            RoomId = new Guid("44d360a3-7433-4405-aaf2-32c2a3eebdf5"),
                            AmenityId = new Guid("44fd1192-34ea-4a44-b8c3-f2716cd744e6")
                        },
                        new
                        {
                            RoomId = new Guid("44d360a3-7433-4405-aaf2-32c2a3eebdf5"),
                            AmenityId = new Guid("48fd1822-33ea-4a44-b8e3-f2716dd744e6")
                        },
                        new
                        {
                            RoomId = new Guid("a6a7acdf-88c2-4fd2-b12e-a387d689f3db"),
                            AmenityId = new Guid("48fd1893-3344-4a45-b7c3-f271acd744e6")
                        },
                        new
                        {
                            RoomId = new Guid("a6a7acdf-88c2-4fd2-b12e-a387d689f3db"),
                            AmenityId = new Guid("48fd1813-3344-4a45-42c2-f2718cd741e5")
                        });
                });

            modelBuilder.Entity("SmartStay.Domain.Entities.RoomImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomImages", (string)null);
                });

            modelBuilder.Entity("SmartStay.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SmartStay.Domain.Entities.Booking", b =>
                {
                    b.HasOne("SmartStay.Domain.Entities.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartStay.Domain.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartStay.Domain.Entities.CancellationLog", b =>
                {
                    b.HasOne("SmartStay.Domain.Entities.Booking", "Booking")
                        .WithOne("CancellationLog")
                        .HasForeignKey("SmartStay.Domain.Entities.CancellationLog", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("SmartStay.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("SmartStay.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("SmartStay.Domain.Entities.PasswordResetToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartStay.Domain.Entities.Payment", b =>
                {
                    b.HasOne("SmartStay.Domain.Entities.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("SmartStay.Domain.Entities.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("SmartStay.Domain.Entities.Review", b =>
                {
                    b.HasOne("SmartStay.Domain.Entities.Room", "Room")
                        .WithMany("Reviews")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartStay.Domain.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartStay.Domain.Entities.Room", b =>
                {
                    b.HasOne("SmartStay.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartStay.Domain.Entities.User", "Renter")
                        .WithMany()
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Renter");
                });

            modelBuilder.Entity("SmartStay.Domain.Entities.RoomAmenity", b =>
                {
                    b.HasOne("SmartStay.Domain.Entities.Amenity", "Amenity")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartStay.Domain.Entities.Room", "Room")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartStay.Domain.Entities.RoomImage", b =>
                {
                    b.HasOne("SmartStay.Domain.Entities.Room", "Room")
                        .WithMany("RoomImages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartStay.Domain.Entities.Amenity", b =>
                {
                    b.Navigation("RoomAmenities");
                });

            modelBuilder.Entity("SmartStay.Domain.Entities.Booking", b =>
                {
                    b.Navigation("CancellationLog");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("SmartStay.Domain.Entities.Room", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");

                    b.Navigation("RoomAmenities");

                    b.Navigation("RoomImages");
                });

            modelBuilder.Entity("SmartStay.Domain.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
